name: aiu_elearn
description: Albukhary International University

version: 2.0.0+7

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  loading_animation_widget: ^1.2.0+4
  flutter_webview_pro: ^3.0.1+4
  url_launcher: ^6.1.12
  connectivity_plus: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/nodata.png
